### ISSUE TITLE
Module not found: Can't resolve '@material-ui/core/styles/createMuiTheme' null

### ISSUE THREAD

**Issue by raphael10-collab** [inrupt/solid-ui-react-demo#36]
(base) raphy@pc:~$ git clone https://github.com/inrupt/solid-ui-react-demo.git
    Cloning into 'solid-ui-react-demo'...
    remote: Enumerating objects: 385, done.
    remote: Counting objects: 100% (385/385), done.
    remote: Compressing objects: 100% (260/260), done.
    remote: Total 385 (delta 184), reused 265 (delta 100), pack-reused 0
    Receiving objects: 100% (385/385), 2.17 MiB | 3.61 MiB/s, done.
    Resolving deltas: 100% (184/184), done.
    (base) raphy@pc:~$ cd solid-ui-react-demo/
    
    (base) raphy@pc:~/solid-ui-react-demo$ yarn
    yarn install v1.22.10
    info No lockfile found.
    warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
    [1/4] Resolving packages...
    warning @inrupt/lit-generated-vocab-common > @types/rdf-js@4.0.2: This is a stub types definition. rdf-js provides its own type definitions, so you do not need this installed.
    warning @inrupt/lit-generated-vocab-common > @rdfjs/data-model > @types/rdf-js@4.0.2: This is a stub types definition. rdf-js provides its own type definitions, so you do not need this installed.
    warning next > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
    warning next > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
    warning babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
    [2/4] Fetching packages...
    info fsevents@2.3.2: The platform "linux" is incompatible with this module.
    info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    warning " > @inrupt/prism-react-components@0.13.5" has incorrect peer dependency "react@^16.8.0".
    warning " > @inrupt/prism-react-components@0.13.5" has incorrect peer dependency "react-dom@^16.8.0".
    warning " > @inrupt/eslint-config-base@0.2.0-alpha.1" has unmet peer dependency "eslint-config-airbnb-base@^14.1.0".
    warning " > @inrupt/eslint-config-react@0.2.0-alpha.1" has incorrect peer dependency "@inrupt/eslint-config-base@^0.1.1".
    [4/4] Building fresh packages...
    success Saved lockfile.
    Done in 38.35s.
    
    (base) raphy@pc:~/solid-ui-react-demo$ yarn dev
    yarn run v1.22.10
    $ next dev
    ready - started server on 0.0.0.0:3000, url: http://localhost:3000
    info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
    error - ./node_modules/@inrupt/prism-react-components/dist/index.es.js:4:0
    Module not found: Can't resolve '@material-ui/core/styles/createMuiTheme'
    null
    event - build page: /next/dist/pages/_error
    wait  - compiling...
    error - ./node_modules/@inrupt/prism-react-components/dist/index.es.js:4:0
    Module not found: Can't resolve '@material-ui/core/styles/createMuiTheme'
    null
    Error: Cannot find module '@material-ui/core/styles/createMuiTheme'
    Require stack:
    - /home/raphy/solid-ui-react-demo/node_modules/@inrupt/prism-react-components/dist/index.js
    - /home/raphy/solid-ui-react-demo/.next/server/pages/_app.js
    - /home/raphy/solid-ui-react-demo/node_modules/next/dist/next-server/server/require.js
    - /home/raphy/solid-ui-react-demo/node_modules/next/dist/next-server/server/load-components.js
    - /home/raphy/solid-ui-react-demo/node_modules/next/dist/next-server/server/api-utils.js
    - /home/raphy/solid-ui-react-demo/node_modules/next/dist/next-server/server/next-server.js
    - /home/raphy/solid-ui-react-demo/node_modules/next/dist/server/next.js
    - /home/raphy/solid-ui-react-demo/node_modules/next/dist/server/lib/start-server.js
    - /home/raphy/solid-ui-react-demo/node_modules/next/dist/cli/next-dev.js
    - /home/raphy/solid-ui-react-demo/node_modules/next/dist/bin/next
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
        at Function.mod._resolveFilename (/home/raphy/solid-ui-react-demo/node_modules/next/dist/build/webpack/require-hook.js:4:1855)
        at Function.Module._load (internal/modules/cjs/loader.js:730:27)
        at Module.require (internal/modules/cjs/loader.js:957:19)
        at require (internal/modules/cjs/helpers.js:88:18)
        at Object.<anonymous> (/home/raphy/solid-ui-react-demo/node_modules/@inrupt/prism-react-components/dist/index.js:7:22)
        at Module._compile (internal/modules/cjs/loader.js:1068:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
        at Module.load (internal/modules/cjs/loader.js:933:32)
        at Function.Module._load (internal/modules/cjs/loader.js:774:14) {
      code: 'MODULE_NOT_FOUND',

![image](https://user-images.githubusercontent.com/70313067/125972839-2a4cfea0-a0dd-4da2-8a79-8ddfb6e34ce0.png)

OS: Ubuntu 20.04
node: v14.17.0

**Comment by InruptSupport** [comment]
Hi @raphael10-collab ,

Thanks for reporting this problem.

It seems like a dependency problem with our UI library. The library is pulling in a newer version of `@material<del>ui/core` and importing a function from there (`createMuiTheme`) directly in a way which wasn’t officially supported and has now been removed (see [this issue](https://github.com/mui</del>org/material-ui/issues/27172)). 

We are working to get this fixed, in the meantime you can use npm instead of yarn, which will consider the package-lock.json in the repo and the problem will not occur.

Cheers,

Nick

Inrupt Support

**Comment by InruptSupport** [comment]
Hi @raphael10-collab ,

Thanks for reporting this problem.

It seems like a dependency problem with our UI library. The library is pulling in a newer version of `@material<del>ui/core` and importing a function from there (`createMuiTheme`) directly in a way which wasn’t officially supported and has now been removed (see [this issue](https://github.com/mui</del>org/material-ui/issues/27172)). 

We are working to get this fixed, in the meantime you can use npm instead of yarn, which will consider the package-lock.json in the repo and the problem will not occur.

Cheers,

Nick

Inrupt Support

**Comment by InruptSupport** [comment]
Hi @raphael10-collab ,

Thanks for reporting this problem.

It seems like a dependency problem with our UI library. The library is pulling in a newer version of `@material<del>ui/core` and importing a function from there (`createMuiTheme`) directly in a way which wasn’t officially supported and has now been removed (see [this issue](https://github.com/mui</del>org/material-ui/issues/27172)). 

We are working to get this fixed, in the meantime you can use npm instead of yarn, which will consider the package-lock.json in the repo and the problem will not occur.

Cheers,

Nick

Inrupt Support

**Comment by InruptSupport** [comment]
Hi @raphael10-collab ,

Thanks for reporting this problem.

It seems like a dependency problem with our UI library. The library is pulling in a newer version of `@material<del>ui/core` and importing a function from there (`createMuiTheme`) directly in a way which wasn’t officially supported and has now been removed (see [this issue](https://github.com/mui</del>org/material-ui/issues/27172)). 

We are working to get this fixed, in the meantime you can use npm instead of yarn, which will consider the package-lock.json in the repo and the problem will not occur.

Cheers,

Nick

Inrupt Support

**Comment by InruptSupport** [comment]
Hi @raphael10-collab ,

Thanks for reporting this problem.

It seems like a dependency problem with our UI library. The library is pulling in a newer version of `@material<del>ui/core` and importing a function from there (`createMuiTheme`) directly in a way which wasn’t officially supported and has now been removed (see [this issue](https://github.com/mui</del>org/material-ui/issues/27172)). 

We are working to get this fixed, in the meantime you can use npm instead of yarn, which will consider the package-lock.json in the repo and the problem will not occur.

Cheers,

Nick

Inrupt Support

**Comment by InruptSupport** [comment]
Hi @raphael10-collab ,

Thanks for reporting this problem.

It seems like a dependency problem with our UI library. The library is pulling in a newer version of `@material<del>ui/core` and importing a function from there (`createMuiTheme`) directly in a way which wasn’t officially supported and has now been removed (see [this issue](https://github.com/mui</del>org/material-ui/issues/27172)). 

We are working to get this fixed, in the meantime you can use npm instead of yarn, which will consider the package-lock.json in the repo and the problem will not occur.

Cheers,

Nick

Inrupt Support

**Comment by kevin-inrupt** [comment]
Hi @raphael10-collab ,

The dependency problem in our UI library, prism has been resolve and version 0.13.6 has been released. The issue should be fixed for you now if you reinstall.

All the best,

Nick.-

Inrupt Support

**Comment by raphael10-collab** [comment]
Thank you!!!
